# Generated by Django 3.1.5 on 2021-01-21 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210121_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='guest_card',
            field=models.PositiveIntegerField(choices=[(2, 2), (5, 5), (6, 6), (7, 7), (9, 9)], default=(2, 2)),
        ),
        migrations.AlterField(
            model_name='game',
            name='host_card',
            field=models.PositiveIntegerField(choices=[(2, 2), (5, 5), (6, 6), (7, 7), (9, 9)], default=(2, 2)),
        ),
    ]
