# Generated by Django 3.1.5 on 2021-01-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20210121_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='guest_card',
            field=models.PositiveIntegerField(choices=[(2, 2), (4, 4), (6, 6), (7, 7), (8, 8)], default=(2, 2)),
        ),
        migrations.AlterField(
            model_name='game',
            name='host_card',
            field=models.PositiveIntegerField(choices=[(2, 2), (4, 4), (6, 6), (7, 7), (8, 8)], default=(2, 2)),
        ),
    ]
