# Generated by Django 3.1.5 on 2021-01-21 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20210121_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='guest_card',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
